---
- hosts: localhost
  connection: local
#  become: true
  tasks:
  - name: Installing AWS-CLI 2.x
    shell: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      ./aws/install -i /usr/local/aws-cli -b /usr/local/bin --update
      ln -nsf /usr/local/bin/aws /usr/bin/aws
      rm -rf awscliv2.zip
  - name: Kubeconfig Setup
    shell: |
      cd ~/github-action-eks-drupal-pipeline/terraform/
      aws eks --region $(terraform output -raw region) update-kubeconfig --name $(terraform output -raw cluster_name)

  - name: Create a Deployment
    kubernetes.core.k8s:
      state: present
      src: ~/github-action-eks-drupal-pipeline/kubernetes/