name: "Terraform Infrastructure Change Management Pipeline with GitHub Actions"
 
on:
  push:
    branches:
      - "master"
 
env:
 # verbosity setting for Terraform logs
 TF_LOG: INFO
 # Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 # S3 bucket for the Terraform state
 BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}

jobs:
 terraform:
   name: "Terraform Infrastructure Change Management"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       working-directory: ./terraform/

   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2
 
     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.3.0
    
     - name: Terraform init
       id: init
       run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
       

     - name: Terraform Plan
       run: terraform plan -no-color
       continue-on-error: true
    
 
     - name: Terraform Plan Status
       if: steps.plan.outcome == 'failure'
       run: exit 1
 
     - name: Terraform Apply
       run: terraform apply -auto-approve 
       continue-on-error: true
       
     - name: Kubernetes config
       uses: imehedi/actions-awscli-v2@latest
       with:
           args: eks update-kubeconfig --name drupal-eks-cluster
       env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: "eu-west-3"
       continue-on-error: true


     - name: Kubernetes Deploy
       uses: actions-hub/kubectl@master
       with:
         args: apply -f ./kubernetes/
       continue-on-error: true

     - name: Terraform Destroy
       id: destroy
       working-directory: ./terraform/
       run: terraform destroy -auto-approve
